import { randomUUID } from "node:crypto";
import type { Request } from "express";
import type multer from "multer";
import type { StorageAdapter } from "@vaultdrop/types";
import { buildVaultStorageKey } from "./local-storage-adapter.js";
import type { FileService } from "../services/file.service.js";

export interface UploadQueryContext {
  vaultId: string;
  folderId: string | null;
}

/**
 * Custom multer `StorageEngine` that streams the uploaded file's bytes
 * directly into a `StorageAdapter` via `putStream`, instead of buffering
 * the whole file into memory the way `multer.memoryStorage()` does.
 *
 * Validation (vault/folder ownership, duplicate-name conflicts) happens
 * here — before any bytes are written to storage — via the same checks
 * `FileService` always performed, just relocated to run before streaming
 * starts instead of after a full buffer was already built. This
 * preserves today's "reject before storing anything" behavior for
 * invalid uploads, now with zero wasted storage writes for rejected
 * requests.
 *
 * The storage key's uniqueness comes from a fresh random UUID generated
 * here — it does not need to (and does not) match the eventual Prisma
 * `File.id`, which is still auto-generated by Prisma as it always was.
 */
export class StreamingMulterStorageEngine implements multer.StorageEngine {
  constructor(
    private readonly storage: StorageAdapter,
    private readonly fileService: FileService,
    private readonly getOwnerId: (req: Request) => string,
    private readonly getUploadQuery: (req: Request) => UploadQueryContext
  ) {}

  _handleFile(
    req: Request,
    file: Express.Multer.File,
    callback: (error?: unknown, info?: Partial<Express.Multer.File>) => void
  ): void {
    this.handle(req, file).then(
      (info) => callback(null, info),
      (error) => callback(error)
    );
  }

  private async handle(
    req: Request,
    file: Express.Multer.File
  ): Promise<Partial<Express.Multer.File>> {
    const ownerId = this.getOwnerId(req);
    const { vaultId, folderId } = this.getUploadQuery(req);

    await this.fileService.assertCanUpload(
      ownerId,
      vaultId,
      folderId,
      file.originalname
    );

    const storageKey = buildVaultStorageKey(
      vaultId,
      randomUUID(),
      file.originalname
    );

    let sizeBytes: number;

    try {
      const meta = await this.storage.putStream(
        storageKey,
        file.stream,
        file.mimetype || "application/octet-stream"
      );
      sizeBytes = meta.sizeBytes;
    } catch (error) {
      // Best-effort cleanup of whatever (possibly partial) bytes made it
      // to storage before the failure, so a failed upload never leaves
      // an orphaned object behind.
      await this.storage.delete(storageKey).catch(() => undefined);
      throw error;
    }

    return {
      path: storageKey,
      size: sizeBytes
    };
  }

  _removeFile(
    _req: Request,
    file: Express.Multer.File,
    callback: (error: Error | null) => void
  ): void {
    if (!file.path) {
      callback(null);
      return;
    }

    this.storage.delete(file.path).then(
      () => callback(null),
      (error) =>
        callback(error instanceof Error ? error : new Error(String(error)))
    );
  }
}